name: Format and Validate Markdown and JSON Schema

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  format-and-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Prettier
      run: npm install -g prettier

    - name: Format Markdown files with Prettier
      run: prettier --check 'schemas/*.md'

    - name: Format JSON Schema with Prettier
      run: prettier --check 'schemas/*.json'

    - name: Install AJV CLI
      run: npm install -g ajv-cli

    - name: Validate JSON Schema files
      run: ajv compile -s schemas/*.json --strict
